-- Demo dataset disabled for now — see git history for the original 8-vendor
-- seed if you want it back. The compose `seed` one-shot still runs this file
-- on every `docker compose up`, but with no statements left it's a no-op, so
-- restarting the app no longer wipes/reloads over real usage data.
